/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2017-11-11 20:55:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import iit.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Cart</title>\r\n");
      out.write("<link\r\n");
      out.write("\thref='http://fonts.googleapis.com/css?family=Open+Sans:600italic,700italic,800italic,400,300,600,700,800'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Pinyon+Script' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Quicksand:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"css/styles_login.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");

		User user = (User)session.getAttribute("user");
		if (user == null) {
			response.sendRedirect(request.getContextPath() + "/signin.jsp");
			return;
		}
		ShoppingCart cart = user.getCart();
		
		// avoid erroneously re-submission
		double flag = Math.random();  
		session.setAttribute("flag", flag + ""); 
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--header starts-->\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<div class=\"top-header\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t<a href=\"./HomeServlet\"><font size=\"6\" color=\"yellow\">");
      out.print(Constant.NAME );
      out.write(" HOTELS</font></a>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<span class=\"menu\"> </span>\r\n");
      out.write("\t\t\t\t<div class=\"m-clear\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"top-menu\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"./HomeServlet\">START</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							if (user.getLevel() == 1) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"scoll\"><a href=\"analytics.jsp\">ANALYTICS</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"scroll\"><a href=\"signout.jsp\">HI, ");
      out.print(user.getUsername());
      out.write("! SIGNOUT?</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

							if(user.getLevel() == 2) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"scroll\"><a href=\"manage.jsp\">MANAGEMENT</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"cart.jsp\" id=\"cartRoom\">CART ");
      out.print((cart != null && !cart.isEmpty() ? "(" + cart.getObjNumber() + ")" : "") );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"reservations.jsp\">RESERVATIONS</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"register.jsp\">REGISTER</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t$(\"span.menu\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t$(\".top-menu ul\").slideToggle(200);\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"js/jquery-ui.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t//ajax change cartRoom quantity\r\n");
      out.write("\t\t\t$(\":text\").change(function(){\r\n");
      out.write("\t\t\t\tvar quantityVal = $.trim(this.value);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar flag = false;\r\n");
      out.write("\t\t\t\tvar reg = /^\\d+$/g;\r\n");
      out.write("\t\t\t\tvar quantity = -1;\r\n");
      out.write("\t\t\t\tif(reg.test(quantityVal)){\r\n");
      out.write("\t\t\t\t\tquantity = parseInt(quantityVal);\r\n");
      out.write("\t\t\t\t\tif(quantity >= 0){\r\n");
      out.write("\t\t\t\t\t\tflag = true;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(!flag){\r\n");
      out.write("\t\t\t\t\talert(\"Invalid input\");\r\n");
      out.write("\t\t\t\t\t$(this).val($(this).attr(\"class\"));\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar $tr = $(this).parent().parent();\r\n");
      out.write("\t\t\t\tvar title = $.trim($tr.find(\"td:eq(1)\").text());\r\n");
      out.write("\t\t\t\tif(quantity == 0){\r\n");
      out.write("\t\t\t\t\tvar flag2 = confirm(\"Are you sure to remove \" + title +\"?\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(flag2){\r\n");
      out.write("\t\t\t\t\t\t$tr.find(\"td:last\").children()[0].click();\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(this).val($(this).attr(\"class\"));\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar flag = confirm(\"Are you sure to update the quantity of \" + title +\"?\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(!flag){\r\n");
      out.write("\t\t\t\t\t$(this).val($(this).attr(\"class\"));\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar url = \"RoomServlet\";\r\n");
      out.write("\t\t\t/*\tvar roomIdStr = $.trim(this.name); */\r\n");
      out.write("\t\t\t\tvar idStr = $.trim(this.name);\r\n");
      out.write("\t\t\t\tvar args = {\"method\":\"updateCart\",\"id\":idStr, \"quantity\":quantityVal, \"time\":new Date()};\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.post(url, args, function(data){\r\n");
      out.write("\t\t\t\t\tvar roomNumber = data.roomNumber;\r\n");
      out.write("\t\t\t\t\tvar objNumber = data.objNumber;\r\n");
      out.write("\t\t\t\t\tvar totalCost = data.totalCost;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#roomNumber\").text(roomNumber);\r\n");
      out.write("\t\t\t\t\t$(\"#objNumber\").text(objNumber);\r\n");
      out.write("\t\t\t\t\t$(\"#cartRoom\").text(\"CART (\" + objNumber + \")\");\r\n");
      out.write("\t\t\t\t\t$(\"#totalCost\").text(totalCost);\r\n");
      out.write("\t\t\t\t}, \"JSON\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"body\" class=\"rooms text-center\">\r\n");
      out.write("\t\t<section id=\"content\">\r\n");
      out.write("\t\t\t<article style=\"margin-left:8%\">\r\n");
      out.write("\t\t\t\t<!-- <h2>Your Shopping Cart</h2><br> -->\t    \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			if(cart == null || cart.isEmpty()) {
			
      out.write("\r\n");
      out.write("\t\t\t\t<h4>Your shopping cart is empty</h4><br>\r\n");
      out.write("\t\t\t\t<a href=\"./HomeServlet\">Back to Home</a>\r\n");
      out.write("\t\t\t");

			} 
			else {
			
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"#\" onclick=\"javascript:history.back(-1);\">Return</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<a href=\"./index.jsp\">Change search</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<a href=\"./RoomServlet?method=clearCart\" onclick=\"return confirm('Clear everything?');\">Clear cart</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<a href=\"./checkout.jsp\">Check out</a>\r\n");
      out.write("\t\t\t\t<br><br><br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div><h3>Your cart has <font color=\"red\" id=\"roomNumber\">");
      out.print(user.getCart().getRoomNumber() );
      out.write("</font> room(s)</h3></div><br>\r\n");
      out.write("\t\t\t\t<div>Total Cost: <font color=\"green\" id=\"totalCost\">$");
      out.print(String.format("%.2f", cart.getTotalCost()) );
      out.write("</font></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<table style=\"border-collapse: separate; border-spacing: 30px 50px;\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">Picture</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">Name</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">Check in</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">Check out</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">Quantity</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">Unit Cost</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">Option</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
	
				for(ShoppingCartRoom cartRoom: cart.getCartRooms()) {
					Room room = cartRoom.getRoom();
					String roomType = room.getRoomType();
					String type = "";
					
					if (roomType.equals("ss")) {
						type = "Standard Single: 1 King Bed";
					} else if (roomType.equals("sd")) {
						type = "Standard Double: 2 Queen Beds";
					} else if (roomType.equals("ls")) {
						type = "Deluxe Single: 1 King Bed";
					} else if (roomType.equals("ld")) {
						type = "Deluxe Double: 2 Queen Beds";
					} else if (roomType.equals("f")) {
						type = "Family Room";
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\"><img src=\"images/");
      out.print(roomType );
      out.write(".jpg\" style=\"width: 300px; height: 200px\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">");
      out.print(type );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">");
      out.print(cartRoom.getFormattedCheckinDate() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">");
      out.print(cartRoom.getFormattedCheckoutDate() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"");
      out.print(cartRoom.getQuantity() );
      out.write("\" type=\"text\" size=\"1\" name=\"");
      out.print(cartRoom.getRoomId() );
      out.write("\" value=\"");
      out.print(cartRoom.getQuantity() );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\"><del><font color=\"red\">$");
      out.print(room.getPrice() );
      out.write("</font></del>&nbsp;<font color=\"green\">");
      out.print(String.format("%.2f", room.getDiscountedPrice()) );
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t<td><a href=\"./RoomServlet?method=removeCartRoom&roomId=");
      out.print(room.getRoomId() );
      out.write("\" class=\"delete\">remove</a></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				}	// end for
				
				for (ShoppingCartRest cartRest: cart.getCartRestaurants()) {
					Restaurant rest = cartRest.getRest();
			
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\"><img src=\"images/");
      out.print(cartRest.getRestId() );
      out.write(".jpg\" style=\"width: 300px; height: 200px\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">");
      out.print(rest.getName() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"");
      out.print(cartRest.getQuantity() );
      out.write("\" type=\"text\" size=\"1\" name=\"");
      out.print(rest.getRid() );
      out.write("\" value=\"");
      out.print(cartRest.getQuantity() );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\"><del><font color=\"red\">$");
      out.print(rest.getPrice() + 8 );
      out.write("</font></del>&nbsp;<font color=\"green\">$");
      out.print(rest.getPrice() );
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t<td><a href=\"./RoomServlet?method=removeCartRest&rid=");
      out.print(rest.getRid() );
      out.write("\" class=\"delete\">remove</a></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t");

			}	// end if
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</article>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t<!-- footer -->\r\n");
      out.write("\t<div class=\"fotter-info\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"hotel-info\">\r\n");
      out.write("\t\t\t\t<h4>Get to Know Us</h4>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Career</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">About</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=hotel-info>\r\n");
      out.write("\t\t\t\t<h4>Apps</h4>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">iOS</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Android</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=hotel-info>\r\n");
      out.write("\t\t\t\t<h4>Let Us Help You</h4>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Help</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Contact Us</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<h6>\r\n");
      out.write("\t\t\t<p>CSP 584 - Project</p>\r\n");
      out.write("\t\t</h6>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
