/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2017-11-11 20:50:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import iit.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>");
      out.print(Constant.NAME );
      out.write(" HOTELS Home</title>\n");
      out.write("<link\n");
      out.write("\thref='http://fonts.googleapis.com/css?family=Open+Sans:600italic,700italic,800italic,400,300,600,700,800'\n");
      out.write("\trel='stylesheet' type='text/css'>\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Pinyon+Script' rel='stylesheet' type='text/css'>\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Quicksand:400,700' rel='stylesheet' type='text/css'>\n");
      out.write("<link href=\"css/bootstrap.css\" rel='stylesheet' type='text/css' />\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t");

		User user = (User) session.getAttribute("user");
		int roomNumber = 0;
	
      out.write("\n");
      out.write("\n");
      out.write("\t<!--header starts-->\n");
      out.write("\t<div class=\"header\">\n");
      out.write("\t\t<div class=\"top-header\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"logo\">\n");
      out.write("\t\t\t\t\t<a href=\"./HomeServlet\"><font size=\"6\" color=\"yellow\">");
      out.print(Constant.NAME );
      out.write(" HOTELS</font></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<span class=\"menu\"> </span>\n");
      out.write("\t\t\t\t<div class=\"m-clear\"></div>\n");
      out.write("\t\t\t\t<div class=\"top-menu\">\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"./HomeServlet\">START</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t");

							if (user == null) {
						
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<li class=\"scroll\"><a href=\"signin.jsp\">SIGN IN</a></li>\n");
      out.write("\t\t\t\t\t\t");

							} else {
								ShoppingCart cart = user.getCart();
								if(user.getLevel() == 1) {
						
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"scoll\"><a href=\"analytics.jsp\">ANALYTICS</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t");

								}
								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<li class=\"scroll\"><a href=\"signout.jsp\">Hi, ");
      out.print(user.getUsername());
      out.write("! SIGN OUT?</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t");

								if(user.getLevel() == 2) {
								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"scroll\"><a href=\"manage.jsp\">MANAGEMENT</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t");

								}
							}
						
      out.write("\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"cart.jsp\">CART</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"reservations.jsp\">RESERVATIONS</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"register.jsp\">REGISTER</a></li>\n");
      out.write("\t\t\t\t\t\t<!-- <li class=\"scroll\"><a href=\"restaurant.jsp\">RESTAURANT</a></li> -->\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t<script>\n");
      out.write("\t\t\t\t\t\t$(\"span.menu\").click(function() {\n");
      out.write("\t\t\t\t\t\t\t$(\".top-menu ul\").slideToggle(200);\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t</script>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"banner\">\n");
      out.write("\t\t\t<div class=\"banner-info text-center\">\n");
      out.write("\t\t\t\t<h3>\n");
      out.write("\t\t\t\t\t<label>Hello,</label> You've Reached\n");
      out.write("\t\t\t\t</h3>\n");
      out.write("\t\t\t\t<h1>");
      out.print(Constant.NAME );
      out.write("</h1>\n");
      out.write("\t\t\t\t<!-- auto-complete search bar -->\n");
      out.write("\t\t\t\t<label for=\"searchHotels\"><font color=\"orange\">Search Hotel:</font></label>&nbsp;\n");
      out.write("               \t<input id=\"searchHotels\" placeholder=\"hotel name\"/>\n");
      out.write("                <br><br>\n");
      out.write("\t\t\t\t<span></span>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<!---start-date-picker---->\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/jquery-ui.css\" />\n");
      out.write("\t<script src=\"js/jquery-ui.js\"></script>\n");
      out.write("\t<script>\n");
      out.write("\t\t$(function() {\n");
      out.write("\t\t\t$(\"#datepicker,#datepicker1\").datepicker();\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t// major cities carousel callback\n");
      out.write("\t\t\t$(\".city\").click(function() {\n");
      out.write("\t\t\t\tvar location = $(this).attr(\"name\");\n");
      out.write("\t\t\t\tvar checkinDate = $(\"#datepicker\").val();\n");
      out.write("\t\t\t\tvar checkoutDate = $(\"#datepicker1\").val();\n");
      out.write("\t\t\t\tvar roomCount = $(\"#country\").val();\n");
      out.write("\t\t\t\twindow.location.href = \"./searchHotels.jsp?checkinDate=\" + checkinDate + \"&checkoutDate=\" \n");
      out.write("\t\t\t\t\t\t+ checkoutDate + \"&roomCount=\" + roomCount + \"&location=\" + location;\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t// auto complete by Ajax\n");
      out.write("\t\t\t$(\"#searchHotels\").autocomplete({\n");
      out.write("\t\t\t\t source: function( request, response ) {\n");
      out.write("\t\t\t\t \tvar url = \"AutocompleteServlet\";\n");
      out.write("\t\t\t\t \tvar args = {\"time\":new Date(), \"term\": request.term};\n");
      out.write("\t\t\t        \n");
      out.write("\t\t\t        $.post(url, args, function(data){\n");
      out.write("\t\t\t        \tresponse(data);\n");
      out.write("\t\t\t        }, \"JSON\");\n");
      out.write("\t\t\t    },\n");
      out.write("\t\t\t    select: function (event, ui) {\n");
      out.write("\t\t            window.location = ui.item.url;\n");
      out.write("\t\t        }\n");
      out.write("\t\t    });\n");
      out.write("\t\t\t\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t</script>\n");
      out.write("\t<!---/End-date-piker---->\n");
      out.write("\t<link type=\"text/css\" rel=\"stylesheet\" href=\"css/JFGrid.css\" />\n");
      out.write("\t<link type=\"text/css\" rel=\"stylesheet\" href=\"css/JFFormStyle-1.css\" />\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/JFCore.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/JFForms.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<!-- Set here the key for your domain in order to hide the watermark on the web server -->\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\t(function() {\n");
      out.write("\t\t\tJC.init({\n");
      out.write("\t\t\t\tdomainKey : ''\n");
      out.write("\t\t\t});\n");
      out.write("\t\t})();\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("\t<div class=\"online_reservation\">\n");
      out.write("\t\t<div class=\"b_room\">\n");
      out.write("\t\t\t<div class=\"booking_room\">\n");
      out.write("\t\t\t\t<div class=\"reservation\">\n");
      out.write("\t\t\t\t\t<!-- <form action=\"./SearchHotelServlet\" method=\"post\"> -->\n");
      out.write("\t\t\t\t\t<form action=\"./searchHotels.jsp\" method=\"get\">\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"span1_of_1 left\">\n");
      out.write("\t\t\t\t\t\t\t\t<h5>Check-in</h5>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"book_date\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"date\" id=\"datepicker\" type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"checkinDate\" value=\"12/08/2017\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonfocus=\"this.value = '';\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = '11/08/2017';}\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"span1_of_1 left\">\n");
      out.write("\t\t\t\t\t\t\t\t<h5>Check-out</h5>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"book_date\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"date\" id=\"datepicker1\" type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"checkoutDate\" value=\"12/10/2017\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonfocus=\"this.value = '';\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = '11/10/2017';}\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"span1_of_1\">\n");
      out.write("\t\t\t\t\t\t\t\t<h5>Number of Rooms</h5> <!----------start section_room----------->\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"section_room\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- <select id=\"country\" onchange=\"change_country(this.value)\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"roomType\" class=\"frm-field required\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"ss\">Standard Single Room</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"sd\">Standard Double Room</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"ls\">Deluxe Single Room</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"ld\">Deluxe Double Room</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"f\">Family Room</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t</select> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"country\" onchange=\"change_country(this.value)\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"roomCount\" class=\"frm-field required\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1\">1 Room</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2\">2 Rooms</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"3\">3 Rooms</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"4\">4 Rooms</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"span1_of_1\">\n");
      out.write("\t\t\t\t\t\t\t\t<h5>Destination</h5>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"zipCode\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"location\" placeholder=\"City, Zip code\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"span1_of_3\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"date_btn\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"view\" onclick=\"alert11()\" type=\"submit\" value=\"View Prices\" style=\"background-color: orange\" />\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<br>\n");
      out.write("\t\n");
      out.write("\t<!---->\n");
      out.write("\t<div class=\"package text-center\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<h3>Major Cities</h3>\n");
      out.write("\t\t\t<link href=\"css/owl.carousel.css\" rel=\"stylesheet\">\n");
      out.write("\t\t\t<script src=\"js/owl.carousel.js\"></script>\n");
      out.write("\t\t\t<script>\n");
      out.write("\t\t\t\t$(document).ready(function() {\n");
      out.write("\t\t\t\t\t$(\"#owl-demo\").owlCarousel({\n");
      out.write("\t\t\t\t\t\titems : 1,\n");
      out.write("\t\t\t\t\t\tlazyLoad : true,\n");
      out.write("\t\t\t\t\t\tautoPlay : true,\n");
      out.write("\t\t\t\t\t\tnavigation : true,\n");
      out.write("\t\t\t\t\t\tnavigationText : false,\n");
      out.write("\t\t\t\t\t\tpagination : false,\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</script>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- //requried-jsfiles-for owl -->\n");
      out.write("\t\t\t<div id=\"owl-demo\" class=\"owl-carousel\">\n");
      out.write("\t\t\t\t<div class=\"item text-center image-grid\">\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><img class=\"city\" name=\"New York\" src=\"images/1_NewYork.jpg\"><br>New York</li>\n");
      out.write("\t\t\t\t\t\t<li><img class=\"city\" name=\"Chicago\" src=\"images/2_Chicago.jpg\"><br>Chicago</li>\n");
      out.write("\t\t\t\t\t\t<li><img class=\"city\" name=\"Los Angeles\" src=\"images/3_LA.jpg\"><br>Los Angeles</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"item text-center image-grid\">\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><img class=\"city\" name=\"San Francisco\" src=\"images/4_SanFrancisco.jpg\"><br>San Francisco</li>\n");
      out.write("\t\t\t\t\t\t<li><img class=\"city\" name=\"Houston\" src=\"images/5_Houston.jpg\"><br>Houston</li>\n");
      out.write("\t\t\t\t\t\t<li><img class=\"city\" name=\"Miami\" src=\"images/6_Miami.jpg\"><br>Miami</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- <div class=\"item text-center image-grid\">\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><a class=\"city\" ><img class=\"city\" name=\"\" src=\"images/1_NewYork.jpg\" alt=\"\"></a><br>New York</li>\n");
      out.write("\t\t\t\t\t\t<li><a class=\"city\"><img class=\"city\" src=\"images/2_Chicago.jpg\" alt=\"\"></a><br>Chicago</li>\n");
      out.write("\t\t\t\t\t\t<li><a class=\"city\"><img class=\"city\" src=\"images/3_LA.jpg\" alt=\"\"></a><br>Los Angeles</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"item text-center image-grid\">\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><a class=\"city\"><img class=\"city\" src=\"images/4_SanFrancisco.jpg\" alt=\"\"></a><br>San Francisco</li>\n");
      out.write("\t\t\t\t\t\t<li><a class=\"city\"><img class=\"city\" src=\"images/5_Houston.jpg\" alt=\"\"></a><br>Houston</li>\n");
      out.write("\t\t\t\t\t\t<li><a class=\"city\"><img class=\"city\" src=\"images/6_Miami.jpg\" alt=\"\"></a><br>Miami</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div> -->\n");
      out.write("\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"rooms text-center\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<h3>Our Room Types</h3>\n");
      out.write("\t\t\t<div class=\"room-grids\">\n");
      out.write("\t\t\t\t<div class=\"col-md-4 room-sec\">\n");
      out.write("\t\t\t\t\t<img src=\"images/ss.jpg\" alt=\"\"\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 300px; height: 183px\"/>\n");
      out.write("\t\t\t\t\t<h4>Standard Single Room</h4>\n");
      out.write("\t\t\t\t\t<p>You can relax and feel at home as all single rooms are\n");
      out.write("\t\t\t\t\t\tfitted with a spacious semi double bed. Some are also fitted with\n");
      out.write("\t\t\t\t\t\ta desk.</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-4 room-sec\">\n");
      out.write("\t\t\t\t\t<img src=\"images/sd.jpg\" alt=\"\"\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 300px; height: 183px\" />\n");
      out.write("\t\t\t\t\t<h4>Standard Double Room</h4>\n");
      out.write("\t\t\t\t\t<p>Most suitable for couples and the size enables you to relax\n");
      out.write("\t\t\t\t\t\tand feel at home. All rooms are also fitted with a desk, a closet\n");
      out.write("\t\t\t\t\t\tand a washlet.</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-4 room-sec\">\n");
      out.write("\t\t\t\t\t<img src=\"images/f.jpg\" alt=\"\"\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 300px; height: 183px\" />\n");
      out.write("\t\t\t\t\t<h4>Family Room</h4>\n");
      out.write("\t\t\t\t\t<p>You can enjoy the family room as if at your own home. All\n");
      out.write("\t\t\t\t\t\tfamily rooms are also fitted with kids' bed and toys</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\n");
      out.write("\t\t\t\t<div class=\"col-md-4 room-sec\">\n");
      out.write("\t\t\t\t\t<img src=\"images/ls.jpg\" alt=\"\"\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 300px; height: 183px\" />\n");
      out.write("\t\t\t\t\t<h4>Deluxe Single Room</h4>\n");
      out.write("\t\t\t\t\t<p>Deluxe double rooms are ideal for one who wishes to\n");
      out.write("\t\t\t\t\t\texperience a romantic holiday escape in Rome or is visiting for a\n");
      out.write("\t\t\t\t\t\tbusiness matter. Deluxe rooms are designed with ultimate guest\n");
      out.write("\t\t\t\t\t\tcomfort in mind at one of the top hotels near Trevi Fountain.</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-4 room-sec\">\n");
      out.write("\t\t\t\t\t<img src=\"images/ld.jpg\" alt=\"\"\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 300px; height: 183px\" />\n");
      out.write("\t\t\t\t\t<h4>Deluxe Double Room</h4>\n");
      out.write("\t\t\t\t\t<p>Elegantly furnished, the Deluxe double is perfect for a\n");
      out.write("\t\t\t\t\t\tcomfortable single occupancy sojourn or a couple’s weekend getaway\n");
      out.write("\t\t\t\t\t\tat one of the best Rome City centre hotels. All Deluxe doubles\n");
      out.write("\t\t\t\t\t\tfeature king-size beds, refined marble bathrooms and work desks.</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"fotter-info\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"hotel-info\">\n");
      out.write("\t\t\t\t<h4>Get to Know Us</h4>\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Career</a>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">About</a>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=hotel-info>\n");
      out.write("\t\t\t\t<h4>Apps</h4>\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">iOS</a>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Android</a>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=hotel-info>\n");
      out.write("\t\t\t\t<h4>Let Us Help You</h4>\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Help</a>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Contact Us</a>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<h6>\n");
      out.write("\t\t\t<p>CSP 584 - Project</p>\n");
      out.write("\t\t</h6>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
