/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2017-11-12 20:22:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import iit.*;

public final class reservation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Reservation</title>\r\n");
      out.write("<link\r\n");
      out.write("\thref='http://fonts.googleapis.com/css?family=Open+Sans:600italic,700italic,800italic,400,300,600,700,800'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Pinyon+Script' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Quicksand:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"css/styles_login.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");

		User user = (User) session.getAttribute("user");
		if (user == null) {
			response.sendRedirect(request.getContextPath() + "/signin.jsp");
			return;
		}
		ShoppingCart cart = user.getCart();
		
		// avoid erroneously re-submission
		double flag = Math.random();  
		session.setAttribute("flag", flag + ""); 
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--header starts-->\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<div class=\"top-header\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t<a href=\"./HomeServlet\"><font size=\"6\" color=\"yellow\">");
      out.print(Constant.NAME );
      out.write(" HOTELS</font></a>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<span class=\"menu\"> </span>\r\n");
      out.write("\t\t\t\t<div class=\"m-clear\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"top-menu\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"./HomeServlet\">START</a></li>\r\n");
      out.write("\t\t\t\t\t");

						if(user.getLevel() == 1) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"scoll\"><a href=\"analytics.jsp\">ANALYTICS</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

						}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"signout.jsp\">HI, ");
      out.print(user.getUsername());
      out.write("SIGNOUT?</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"cart.jsp\" id=\"cartRoom\">CART ");
      out.print((cart != null && !cart.isEmpty() ? "(" + cart.getObjNumber() + ")" : "") );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"reservations.jsp\">RESERVATIONS</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"register.jsp\">REGISTER</a></li>\r\n");
      out.write("\t\t\t\t\t\t<!-- <li class=\"scroll\"><a href=\"restaurant.jsp\">RESTAURANT</a></li> -->\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t$(\"span.menu\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t$(\".top-menu ul\").slideToggle(200);\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");

		Integer oid = Integer.parseInt(request.getParameter("oid"));
		Order order = user.getOrdersMap().get(oid);
		System.out.println("order: " + order);
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"body\" class=\"rooms text-center\">\r\n");
      out.write("\t\t<section id=\"content\">\r\n");
      out.write("\t\t\t<article style=\"margin-left:5%\"><h2>Your Reservation &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Time: ");
      out.print(order.getFormattedOrderTime() );
      out.write("</h2></article>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<article style=\"margin-left:5%\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t");

				if(user.getOrdersMap() != null && !user.isOrderEmpty()) {
					out.println("<table frame='void' style=\"border-collapse:separate; border-spacing:25px 45px;\">");
					out.println("<tr>");
					out.println("<td align=\"center\">Hotel</td>");
					out.println("<td align=\"center\">Picture</td>");
					out.println("<td align=\"center\">Name</td>");
					out.println("<td align=\"center\">Check in</td>");
					out.println("<td align=\"center\">Check out</td>");
					out.println("<td align=\"center\">Unit Price</td>");
					out.println("<td align=\"center\">Quantity</td>");
					out.println("</tr>");
					
					if (order.getOrderRooms() == null || (order.getOrderRooms() != null && order.getOrderRooms().isEmpty())) {
						order.setOrderRooms(OrderRoomDAO.getOrderRoomsByOrder(order));
						order.setOrderRests(OrderRestDAO.getOrderRestsByOrder(order));
					}
					
					for (OrderRoom orderRoom : order.getOrderRooms()) {
						String roomId = orderRoom.getRoomId();
						Room room = RoomDAO.getRoomById(roomId);
						String roomType = room.getRoomType();
						String type = "";
						if (roomType.equals("ss")) {
							type = "Standard Single: 1 King Bed";
						} else if (roomType.equals("sd")) {
							type = "Standard Double: 2 Queen Beds";
						} else if (roomType.equals("ls")) {
							type = "Deluxe Single: 1 King Bed";
						} else if (roomType.equals("ld")) {
							type = "Deluxe Double: 2 Queen Beds";
						} else if (roomType.equals("f")) {
							type = "Family Room";
						}
						String hid = orderRoom.getHid();
						
						out.println("<tr>");
						out.println("<td><a href=\"./hotelInfo.jsp?hid=" + hid + "\">" + HotelDAO.getNameById(hid) + "</a></td>");
						out.println("<td><img src=\"images/" + roomType + ".jpg\" style=\"width:128px;height:128px;\"></a></td>");
						out.println("<td>" + type + "</td>");
						out.println("<td>" + orderRoom.getFormattedCheckinDate() + "</td>");
						out.println("<td>" + orderRoom.getFormattedCheckoutDate() + "</td>");
						out.println("<td align=\"center\"><font color=\"green\">$" + String.format("%.2f", orderRoom.getPrice()) + "</font></td>");
						out.println("<td align=\"center\">" + orderRoom.getQuantity() + "</td>");
						out.println("</tr>");
					}
					
					for (OrderRest orderRest: order.getOrderRests()) {
						String restId = orderRest.getRestId();
						Restaurant rest = RestaurantDAO.getRestaurantById(restId);
						
						out.println("<tr>");
						out.println("<td></td>");
						out.println("<td><img src=\"images/" + restId + ".jpg\" style=\"width:128px;height:128px;\"></a></td>");
						out.println("<td>" + rest.getName() + "</td>");
						out.println("<td></td>");
						out.println("<td></td>");
						out.println("<td align=\"center\"><font color=\"green\">$" + String.format("%.2f", rest.getPrice()) + "</font></td>");
						out.println("<td align=\"center\">" + orderRest.getQuantity() + "</td>");
						out.println("</tr>");
					}
					out.println("<tr></tr>");
					out.println("<tr><td></td>");
					out.println("<td>Order total cost: $" + String.format("%.2f", order.getCost()) + "</td>");
					out.println("<td><a href=\"./reservations.jsp\">Back to Reservations</a></td>");
					out.println("<td><a href=\"./HomeServlet\">Continue Booking</a></td></tr>");
					out.println("</table>");
				}
			
      out.write("\r\n");
      out.write("\t\t\t</article>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t<div class=\"fotter-info\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"hotel-info\">\r\n");
      out.write("\t\t\t\t<h4>Get to Know Us</h4>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Career</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">About</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=hotel-info>\r\n");
      out.write("\t\t\t\t<h4>Apps</h4>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">iOS</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Android</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=hotel-info>\r\n");
      out.write("\t\t\t\t<h4>Let Us Help You</h4>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Help</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Contact Us</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<h6>\r\n");
      out.write("\t\t\t<p>CSP 584 - Project</p>\r\n");
      out.write("\t\t</h6>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
