/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2017-11-12 07:36:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import iit.*;
import java.util.*;

public final class restaurant_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Restaurant Coupon</title>\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Open+Sans:600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Pinyon+Script' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Quicksand:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel='stylesheet' type='text/css'/>\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\"/>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

	User user = (User)session.getAttribute("user");
	if (user == null) {
		response.sendRedirect(request.getContextPath() + "/signin.jsp");
		return;
	}
	ShoppingCart cart = user.getCart();
	String hid = request.getParameter("hid");
	
	// avoid erroneously re-submission
	double flag = Math.random();  
	session.setAttribute("flag", flag + ""); 
	
	String checkinDate = request.getParameter("checkinDate");
	String checkoutDate = request.getParameter("checkoutDate");
	String roomCount = request.getParameter("roomCount");
	Integer count = Integer.parseInt(roomCount);
	

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!--header starts-->\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("\t <div class=\"top-header\">\r\n");
      out.write("\t\t <div class=\"container\">\r\n");
      out.write("\t\t\t <div class=\"logo\">\r\n");
      out.write("\t\t\t\t <a href=\"./HomeServlet\"><img src=\"images/logo.png\"/></a>\r\n");
      out.write("\t\t\t <div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t\t <span class=\"menu\"> </span>\r\n");
      out.write("\t\t\t <div class=\"m-clear\"></div>\r\n");
      out.write("\t\t\t <div class=\"top-menu\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"./HomeServlet\">START</a></li>\r\n");
      out.write("\t\t\t\t\t");

						if(user.getLevel() == 1) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"scoll\"><a href=\"analytics.jsp\">ANALYTICS</a></li>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"signout.jsp\">HI, ");
      out.print(user.getUsername());
      out.write("! SIGNOUT?</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"cart.jsp\">CART ");
      out.print((cart != null && !cart.isEmpty() ? "(" + cart.getObjNumber() + ")" : ""));
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"reservations.jsp\">RESERVATIONS</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"register.jsp\">REGISTER</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t$(\"span.menu\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t$(\".top-menu ul\").slideToggle(200);\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Restaurant coupons -->\r\n");
      out.write("\t<div class=\"rooms text-center\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h3>Discounted Buffet Restaurants</h3>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

				String restId = (String)request.getAttribute("rid");
				if(restId != null && !restId.equals("")) {
			
      out.write("\r\n");
      out.write("\t\t\t\t\t<h5><font color=\"red\">");
      out.print(RestaurantDAO.getRestNameById(restId) );
      out.write("</font> \r\n");
      out.write("\t\t\t\t\tadded to <a href=\"./cart.jsp?hid=");
      out.print(hid );
      out.write("&checkinDate=");
      out.print(checkinDate );
      out.write("&checkoutDate=");
      out.print(checkoutDate );
      out.write("&roomCount=");
      out.print(roomCount );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<font color=\"green\">Cart</font></a>\r\n");
      out.write("\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table style=\"border-collapse: separate; border-spacing: 30px 50px;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\">Picture</td>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\">Name</td>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\">Price per Person</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						for(Restaurant rest: RestaurantDAO.getRestaurantsOfCity(hid.substring(0, 1))) {	
							String rid = rest.getRid();
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\"><img src=\"images/");
      out.print(rid );
      out.write(".jpg\" style=\"width: 300px; height: 200px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\">");
      out.print(rest.getName() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\"><del><font color=\"red\">$");
      out.print(rest.getPrice() + 8 );
      out.write("</font></del>&nbsp;<font color=\"green\">");
      out.print(rest.getPrice() );
      out.write("</font><br><br>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<form action=\"./RoomServlet\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- out.println(\"<input type=\\\"hidden\\\" name=\\\"method\\\" value=\\\"addToCart\\\">\"); -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"flag\" value=\"");
      out.print(flag );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"method\" value=\"addToCart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"hid\" value=\"");
      out.print(hid );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"checkinDate\" value=\"");
      out.print(checkinDate );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"checkoutDate\" value=\"");
      out.print(checkoutDate );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"rid\" value=\"");
      out.print(rid );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"roomCount\" value=\"");
      out.print(roomCount );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Book\" style=\"background-color: orange\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- footer -->\r\n");
      out.write("\t<div class=\"fotter-info\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"hotel-info\">\r\n");
      out.write("\t\t\t\t<h4>Get to Know Us</h4>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Career</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">About</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=hotel-info>\r\n");
      out.write("\t\t\t\t<h4>Apps</h4>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">iOS</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Android</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=hotel-info>\r\n");
      out.write("\t\t\t\t<h4>Let Us Help You</h4>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Help</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Contact Us</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<h6>\r\n");
      out.write("\t\t\t<p>CSP 584 - Project</p>\r\n");
      out.write("\t\t</h6>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
