/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2017-11-11 20:51:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import iit.*;
import java.util.*;

public final class searchHotels_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


		private boolean isCity(String location) {
			location = location.toLowerCase();
			for (int i = 0; i < location.length(); i++) {
				if (location.charAt(i) < 'a' && location.charAt(i) > 'z') {
					return false;
				}
			}
			return true;
		}
		
		private boolean isZipCode(String location) {
			for (int i = 0; i < location.length(); i++) {
				if (location.charAt(i) < '0' || location.charAt(i) > '9') {
					return false;
				}
			}
			return true;
		}
	
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Search Hotels</title>\r\n");
      out.write("<link\r\n");
      out.write("\thref='http://fonts.googleapis.com/css?family=Open+Sans:600italic,700italic,800italic,400,300,600,700,800'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Pinyon+Script' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Quicksand:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jquery-ui.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"css/JFGrid.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"css/JFFormStyle-1.css\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

		String checkinDate = request.getParameter("checkinDate");
		String checkoutDate = request.getParameter("checkoutDate");
		String roomCount = request.getParameter("roomCount");
		String location = request.getParameter("location");
		System.out.println(checkinDate);
		System.out.println(checkoutDate);
		System.out.println(roomCount);
		System.out.println(location);
		
		if(location.equals("")) {
			out.println("<script>alert(\"Please input your destination or choose from major cities below.\")");
			out.println("window.location.href = \"./index.jsp\"");
			out.println("</script>");
			return;
		}
	
	
		// if input is zip-code
		ArrayList<Hotel> hotelList = new ArrayList<Hotel>();
		if (isZipCode(location)) {
			Integer zipCodeRange = Integer.parseInt(location) / 10000;
			hotelList = HotelDAO.getHotelsByZipCode(zipCodeRange);
		}
		else if (isCity(location)) {	// if input is city
			hotelList = HotelDAO.getHotelsByCity(location);
		}
		
		if(hotelList.isEmpty()) {
			out.println("<script>alert(\"Sorry, the location that you are looking for is unavailable.\")");
			out.println("window.location.href = \"./index.jsp\"");
			out.println("</script>");
			return;
		}
		
		User user = (User) session.getAttribute("user");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--header starts-->\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<div class=\"top-header\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t<a href=\"./HomeServlet\"><font size=\"6\" color=\"yellow\">");
      out.print(Constant.NAME );
      out.write(" HOTELS</font></a>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<span class=\"menu\"> </span>\r\n");
      out.write("\t\t\t\t<div class=\"m-clear\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"top-menu\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"./HomeServlet\">START</a></li>\r\n");
      out.write("\t\t\t\t\t");

					if (user == null) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"signin.jsp\">SIGN IN</a></li>\r\n");
      out.write("\t\t\t\t\t");

					} else {
						ShoppingCart cart = user.getCart();
						if(user.getLevel() == 1) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"scoll\"><a href=\"analytics.jsp\">ANALYTICS</a></li>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"signout.jsp\">HI, ");
      out.print(user.getUsername());
      out.write("! SIGNOUT?</a></li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");

						if(user.getLevel() == 2) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"manage.jsp\">MANAGEMENT</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

						}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"cart.jsp\">CART ");
      out.print((cart != null && !cart.isEmpty() ? "(" + cart.getRoomNumber() + ")" : "") );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"reservations.jsp\">RESERVATIONS</a></li>\r\n");
      out.write("\t\t\t\t\t");

					}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"scroll\"><a href=\"register.jsp\">REGISTER</a></li>\r\n");
      out.write("\t\t\t\t\t\t<!-- <li class=\"scroll\"><a href=\"restaurant.jsp\">RESTAURANT</a></li> -->\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t$(\"span.menu\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t$(\".top-menu ul\").slideToggle(200);\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"banner\">\r\n");
      out.write("\t\t\t<div class=\"banner-info text-center\">\r\n");
      out.write("\t\t\t\t<h1>");
      out.print(Constant.NAME );
      out.write(" near ");
      out.print(location );
      out.write("</h1>\r\n");
      out.write("\t\t\t\t<h2>");
      out.print(checkinDate );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(checkoutDate );
      out.write("</h2>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!---start-date-picker---->\r\n");
      out.write("\t<script src=\"js/jquery-ui.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#datepicker,#datepicker1\").datepicker();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!---/End-date-piker---->\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/JFCore.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/JFForms.js\"></script>\r\n");
      out.write("\t<!-- Set here the key for your domain in order to hide the watermark on the web server -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t(function() {\r\n");
      out.write("\t\t\tJC.init({\r\n");
      out.write("\t\t\t\tdomainKey : ''\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t})();\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div class=\"online_reservation\">\r\n");
      out.write("\t\t<div class=\"b_room\">\r\n");
      out.write("\t\t\t<div class=\"booking_room\">\r\n");
      out.write("\t\t\t\t<div class=\"reservation\">\r\n");
      out.write("\t\t\t\t\t<form action=\"./searchHotels.jsp\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"span1_of_1 left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5>Check-in</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"book_date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"date\" id=\"datepicker\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"checkinDate\" value=\"");
      out.print(checkinDate );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonfocus=\"this.value = '';\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = '11/08/2017';}\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"span1_of_1 left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5>Check-out</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"book_date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"date\" id=\"datepicker1\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"checkoutDate\" value=\"");
      out.print(checkoutDate );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonfocus=\"this.value = '';\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = '11/10/2017';}\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"span1_of_1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5>Room type</h5> <!----------start section_room----------->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"section_room\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"country\" onchange=\"change_country(this.value)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"roomCount\" class=\"frm-field required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1\">1 Room</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2\">2 Rooms</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"3\">3 Rooms</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"4\">4 Rooms</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"span1_of_1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5>Destination</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"zipCode\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"location\" placeholder=\"City, Zip code\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"span1_of_3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"date_btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Update Search\" style=\"background-color: orange\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"body\" class=\"rooms text-center\">\r\n");
      out.write("\t\t<section id=\"content\">\r\n");
      out.write("\t\t\t<article>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					if(hotelList.isEmpty()) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<h3>No hotel available by your search</h3>\r\n");
      out.write("\t\t\t\t");

					} 
					else {
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<table style=\"border-collapse: separate; border-spacing: 30px 50px;\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">Picture</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">Hotel</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">Hotel Rating</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">Price from</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">Options</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							for(Hotel hotel: hotelList) {	
								String hid = hotel.getHid();
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><a href=\"./hotelInfo.jsp?hid=");
      out.print(hid );
      out.write("\"><img src=\"images/");
      out.print(hotel.getImage() );
      out.write(".jpg\" style=\"width: 300px; height: 200px\"></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><h3><a href=\"./hotelInfo.jsp?hid=");
      out.print(hid );
      out.write('"');
      out.write('>');
      out.print(hotel.getName() );
      out.write("</a></h3><br><br>");
      out.print(hotel.getAddress() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\">");
      out.print(hotel.getAvgRating() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\">");
      out.print((RoomDAO.getLowestPriceOfHotel(hid) == Double.MAX_VALUE ? "" : "$" + RoomDAO.getLowestPriceOfHotel(hid)) );
      out.write("</td>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form action=\"./bookRooms.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- out.println(\"<input type=\\\"hidden\\\" name=\\\"method\\\" value=\\\"addToCart\\\">\"); -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <input type=\"hidden\" name=\"index\" value=\"1\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"hid\" value=\"");
      out.print(hid );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"checkinDate\" value=\"");
      out.print(checkinDate );
      out.write("\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"checkoutDate\" value=\"");
      out.print(checkoutDate );
      out.write("\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"roomCount\" value=\"");
      out.print(roomCount );
      out.write("\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"View Rooms\" style=\"background-color: orange\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <input type=\"submit\" value=\"View prices\" style=\"background-color: orange\" /> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</article>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"fotter-info\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"hotel-info\">\r\n");
      out.write("\t\t\t\t<h4>Get to Know Us</h4>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Career</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">About</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=hotel-info>\r\n");
      out.write("\t\t\t\t<h4>Apps</h4>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">iOS</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Android</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=hotel-info>\r\n");
      out.write("\t\t\t\t<h4>Let Us Help You</h4>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Help</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"color: rgba(237, 237, 237, 0.87)\">Contact Us</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<h6>\r\n");
      out.write("\t\t\t<p>CSP 584 - Project</p>\r\n");
      out.write("\t\t</h6>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
